### ISSUE TITLE
Why you need `form` here? 

### ISSUE THREAD

**Issue by bordi** [rufijey/FrontLab2#1]
https://github.com/rufijey/FrontLab2/blob/30e0173ff02edf1de54ff12ecfd843b7d80c871b/forma.html#L206

**Comment by rufijey** [comment]
Sorry, I messed up, the div tag should have been there

**Comment by bordi** [comment]
> Sorry, I messed up, the div tag should have been there

Please change this and I will check the lab as done

**Comment by rufijey** [comment]
[``](https://github.com/rufijey/FrontLab2/blob/de857ed77db982eebc6a91b452a6a17efc21be86/forma.html#L206C1-L206C36)
I changed it

**Comment by rufijey** [comment]
https://github.com/rufijey/FrontLab2/blob/de857ed77db982eebc6a91b452a6a17efc21be86/forma.html#L206C1-L206C36
I changed it

**Comment by bordi** [comment]
> https://github.com/rufijey/FrontLab2/blob/de857ed77db982eebc6a91b452a6a17efc21be86/forma.html#L206C1-L206C36 I changed it

![image](https://github.com/rufijey/FrontLab2/assets/5034399/2f70b06d-8898-4e3d-aa57-edd1cdf9b734)
